#!/bin/csh
set thereiserr=0

if (-e vasp.out.static) then
  foreach errmsg ( "segmen" "SIGDEV" "cnorm" )
    grep -i -q $errmsg vasp.out.static
    if ( $status == 0 ) then
      set thereiserr=1
    endif
  end
endif

if (-e vasp.out.relax) then
  foreach errmsg ( "non-integer" )
    grep -i -q $errmsg vasp.out.relax
    if ( $status == 0 ) then
      set thereiserr=1
    endif
  end
endif

if ( $thereiserr == 1 && x$1 == "x-e" ) then
  echo "An error occured during this vasp run. Check vasp.out.static and vasp.out.relax for more information." >! error
endif

if ( $thereiserr == 1 && x$1 == "x-p" ) then
  echo Error in `pwd`
endif

exit $thereiserr
