#!/bin/bash
for elem in `ls -1 | grep -v -e ZZ -e data -e set | sed 's/_.*//g' | sort -u`
do
  if [ ! -e $elem ]
  then
    echo == $elem
    for suff in pv sv 3
    do
	if [ -e ${elem}_${suff} ]
	then
	    ln -s ${elem}_${suff} ${elem}
	    echo ln -s ${elem}_${suff} ${elem}
	    break
	fi
    done
  fi
done

