#!/bin/sh
for num in 0 1 2 3 4 5 6 7 8 9 10 11 12 13
do
  ./vctriv -l=../../conf/tms2013/bccaug.in -v=0.1 -s=5000 -n=${num} > ../../conf/tms2013/vcbcc${num}.out
done
sspp < bccaug.sspp | cellcvrt.exe -ss=1 -c | tail -n +7 > bccaugsup.out
