#!/bin/bash
#!/bin/bash
awk '{
  maxlen=80;
  minlen=5;
  line=$0;
  while (length(line)>maxlen) {
    cut=maxlen;
    while (1) {
      while (cut>minlen && index(" -+",substr(line,cut,1)) == 0) {cut--;}
      if (cut<=minlen) {cut=maxlen; break;}
      if(substr(line,cut-1,1)!="E") break;
      cut--;
    }
    print substr(line,1,cut-1);
    line="    " substr(line,cut);
  }
  print line;
}'
