#!/bin/bash
myopt='
-kT=0.25
-mu0=2.0
-mu1=6.0
-dmu=0.05
-nlink=25
-nstepequil=10000
-nstepmax=100000
-verbstep=1000
'
./pathint.exe $myopt

awk '{print $1}' dump.out  > x.in
awk '{print $2,$3,$4,$5,$6,$7}' dump.out  > y.in
lsfit.exe -1 -x=x.in -y=y.in -p | awk '
BEGIN {c=0; r=0;}
{
if ($1=="") {maxr=r; r=0; c++;}
else {
  a[r,c]=$1;
  r++;
}
}
END {
maxc=c;
for (r=0; r<=maxr; r++ ) {
  for (c=0; c<=maxc; c++) {
    printf a[r,c] " "
  }
  print "";
}
}' > dump.tmp
paste x.in dump.tmp > dump.in

./pathint.exe -readmv $myopt | grep ne > path.out

